python tfrun.py summary_metadata.csv config_scan.json '{"activations":["relu"],"losses":["mse"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/relu_mse_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["relu"],"losses":["mae"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/relu_mae_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["relu"],"losses":["kl_divergence"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/relu_kl_divergence_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["leaky_relu"],"losses":["mse"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/leaky_relu_mse_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["leaky_relu"],"losses":["mae"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/leaky_relu_mae_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["leaky_relu"],"losses":["kl_divergence"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/leaky_relu_kl_divergence_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["para_relu"],"losses":["mse"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/para_relu_mse_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["para_relu"],"losses":["mae"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/para_relu_mae_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["para_relu"],"losses":["kl_divergence"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/para_relu_kl_divergence_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["sigmoid"],"losses":["mse"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/sigmoid_mse_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["sigmoid"],"losses":["mae"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/sigmoid_mae_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["sigmoid"],"losses":["kl_divergence"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/sigmoid_kl_divergence_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["softmax"],"losses":["mse"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/softmax_mse_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["softmax"],"losses":["mae"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/softmax_mae_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["softmax"],"losses":["kl_divergence"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/softmax_kl_divergence_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["softplus"],"losses":["mse"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/softplus_mse_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["softplus"],"losses":["mae"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/softplus_mae_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["softplus"],"losses":["kl_divergence"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/softplus_kl_divergence_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["softsign"],"losses":["mse"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/softsign_mse_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["softsign"],"losses":["mae"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/softsign_mae_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["softsign"],"losses":["kl_divergence"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/softsign_kl_divergence_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["tanh"],"losses":["mse"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/tanh_mse_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["tanh"],"losses":["mae"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/tanh_mae_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["tanh"],"losses":["kl_divergence"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/tanh_kl_divergence_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["selu"],"losses":["mse"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/selu_mse_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["selu"],"losses":["mae"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/selu_mae_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["selu"],"losses":["kl_divergence"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/selu_kl_divergence_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["elu"],"losses":["mse"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/elu_mse_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["elu"],"losses":["mae"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/elu_mae_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["elu"],"losses":["kl_divergence"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/elu_kl_divergence_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["exponential"],"losses":["mse"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/exponential_mse_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["exponential"],"losses":["mae"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/exponential_mae_0.4.out
python tfrun.py summary_metadata.csv config_scan.json '{"activations":["exponential"],"losses":["kl_divergence"],"epochs":1000,"validation_split":0.4}' 2>&1 > runs/exponential_kl_divergence_0.4.out
